/*----- PROTECTED REGION ID(RadCtrl::ClassFactory.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        ClassFactory.cpp
//
// description : C++ source for the class_factory method of the DServer
//               device class. This method is responsible for the creation of
//               all class singleton for a device server. It is called
//               at device server startup.
//
// project :     RadControl
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <tango.h>
#include <RadCtrlClass.h>

//	Add class header files if needed


/**
 *	Create RadCtrl Class singleton and store it in DServer object.
 */

void Tango::DServer::class_factory()
{
	//	Add method class init if needed
	add_class(RadCtrl_ns::RadCtrlClass::init("RadCtrl"));
}
/*----- PROTECTED REGION END -----*/	//	RadCtrl::ClassFactory.cpp
